services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWUSER_ID: ${WWWUSER_ID:-1000}
                WWWGROUP_ID: ${WWWGROUP_ID:-1000}
        tty: true
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - '../:/app'
            - 'sail-profile:/home/sail:cached'
            - '/home/sail/.vscode-server'
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-profile:
